CREATE TABLE W2V_TOKEN (uniprot_id VARCHAR(16), type VARCHAR(16), token VARCHAR(64), start INT, end INT);
CREATE TABLE W2V_PROTEIN (uniprot_id VARCHAR(16), start INT, end INT);

# load proteins - took 13mins
LOAD DATA LOCAL INFILE '/data/dev/ucl/data/protein/uniprotkb-2759_78494531_1000.dat' INTO TABLE W2V_PROTEIN FIELDS TERMINATED BY '|';
CREATE INDEX PTN_IDX ON W2V_PROTEIN (UNIPROT_ID);


#
# ------- CREATING THE PRE-CORPUS -----------
#

# select unique pfam tokens 
SELECT DISTINCT TOKEN FROM W2V_TOKEN WHERE TYPE='PFAM'; # this took 8min 15s and returned 20,725 items


# ---- Looping

# return first 20 rows
SELECT * FROM W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 20;

# The combination of these 2 separate queries does the same - rows presumably start at zero
# starting at 0, return first 10 rows
SELECT * FROM W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 0,10;

# starting at 10, return next 10 rows 
SELECT * FROM W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 10,10;


# from chtgpt
SELECT t1.column1, t1.column2, t2.column3
FROM table1 AS t1
INNER JOIN table2 AS t2 ON t1.common_column = t2.common_column;


# this works - using limit 200000,40000 returned in 3.248 at command prompt
SELECT T1.UNIPROT_ID, T1.START, T1.END, T2.TYPE, T2.TOKEN, T2.START, T2.END FROM W2V_PROTEIN AS T1 INNER JOIN W2V_TOKEN AS T2 ON T1.UNIPROT_ID = T2.UNIPROT_ID LIMIT 200000, 40000;

# this also works - using limit 200000,40000 returned in 3.248 at command prompt
SELECT T1.UNIPROT_ID, T1.START, T1.END, T2.TYPE, T2.TOKEN, T2.START, T2.END FROM W2V_PROTEIN T1 INNER JOIN W2V_TOKEN T2 ON T1.UNIPROT_ID = T2.UNIPROT_ID LIMIT 200000, 40000;
SELECT T1.UNIPROT_ID, T1.START, T1.END, T2.TYPE, T2.TOKEN, T2.START, T2.END FROM W2V_PROTEIN T1 INNER JOIN W2V_TOKEN T2 ON T1.UNIPROT_ID = T2.UNIPROT_ID LIMIT 0, 100;


#
# THIS QUERY WORKS AND REDTURNS ALL TEH DETAIL I NEED
#
SELECT W2V_PROTEIN.*, W2V_TOKEN.*
FROM (
    SELECT UNIPROT_ID, START, END
    FROM W2V_PROTEIN
    ORDER BY UNIPROT_ID
    LIMIT 0, 30) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID;

# ALSO WORKS ON ONE LINE DIRECT IN MYSQL COMMAND - BUT THIS TOTALLY HANGS IN PYTHON
SELECT W2V_PROTEIN.*, W2V_TOKEN.* FROM ( SELECT UNIPROT_ID, START, END FROM W2V_PROTEIN W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 2, 2) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID;


mysql -h my.db.com -u usrname--password=pass db_name -e 'SELECT foo FROM bar' > /tmp/myfile.txt

mysql -h $endpoint -P 3306 -u admin W2V -p -e 'DESCRIBE W2V_TOKEN' > sql_test.txt

mysql -h $endpoint -P 3306 -u admin W2V -p -e 'SELECT W2V_PROTEIN.*, W2V_TOKEN.* FROM ( SELECT UNIPROT_ID, START, END FROM W2V_PROTEIN W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 0, 30) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID' > sql_test.txt

mysql -h my.db.com -u usrname--password=pass db_name -e 'SELECT W2V_PROTEIN.*, W2V_TOKEN.* FROM ( SELECT UNIPROT_ID, START, END FROM W2V_PROTEIN W2V_PROTEIN ORDER BY UNIPROT_ID LIMIT 0, 30) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID' > sql_test.txt




# DOESN:T RETURN UNIPROT DETAILS
SELECT W2V_PROTEIN.*, W2V_TOKEN.*
FROM (
    SELECT UNIPROT_ID
    FROM W2V_PROTEIN
    ORDER BY UNIPROT_ID
    LIMIT 0, 30) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID;

# THIS DEFINITELY WORKS AT THE COMMAND LINEE
# -- SEEMS TO WORK - 100,000 executions takes 2.625s
# -- SEEMS TO WORK - 500,000 executions takes 16s
SELECT W2V_PROTEIN.UNIPROT_ID, W2V_TOKEN.*
FROM (
    SELECT UNIPROT_ID
    FROM W2V_PROTEIN
    ORDER BY UNIPROT_ID
    LIMIT 100) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID;


# THIS ALSO WORKS ON THE COMMADN LINE
SELECT W2V_PROTEIN.UNIPROT_ID, W2V_TOKEN.*
FROM (
    SELECT UNIPROT_ID
    FROM W2V_PROTEIN
    ORDER BY UNIPROT_ID
    LIMIT 0, 30) AS W2V_PROTEIN INNER JOIN W2V_TOKEN AS W2V_TOKEN ON W2V_PROTEIN.UNIPROT_ID = W2V_TOKEN.UNIPROT_ID;


SELECT * FROM employees
LIMIT 1000
INTO OUTFILE '/var/lib/mysql-files/employees.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';

SELECT * FROM W2V_TOKEN ORDER BY UNIPROT_ID LIMIT 20
INTO OUTFILE '20_tokens.txt'
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n';